name: Manual .NET Build

on:
  workflow_dispatch

jobs:
  pring-runtime-context:
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ”” start build process
        run: echo "  Build process has started..."

      - name: ğŸ¤ Show runtime context 
        run: |
          echo " ğŸ”§ Runner OS: ${{ runner.os }}"
          echo " ğŸ“¦ Repository: ${{ github.repository }}"
          echo "ğŸ‰ workflow: ${{ github.workflow }}"
          echo " ğŸtriggred by: ${{ github.event_name }}"
          echo " ğŸ¤·â€â™€ï¸ Actor: " {{ github.actor }}"
          echo " ğŸ‘Œ Run number: "{{github.run_number}}"
          echo " ğŸŒ³ Branch: ${{github.ref}}"
